### ISSUE TITLE
won't compile with rustc 1.0.0

### ISSUE THREAD

**Issue by postmodern** [alexcrichton/tar-rs#24]
Was trying to build cargo master and got this error:

<pre>
/home/hal/.cargo/registry/src/github.com-1ecc6299db9ec823/tar-0.2.11/src/lib.rs:190:27: 190:47 error: mismatched types:
 expected `i32`,
    found `u32`
(expected i32,
    found u32) [E0308]
/home/hal/.cargo/registry/src/github.com-1ecc6299db9ec823/tar-0.2.11/src/lib.rs:190             perm.set_mode(mode as libc::mode_t);
                                                                                                              ^~~~~~~~~~~~~~~~~~~~
/home/hal/.cargo/registry/src/github.com-1ecc6299db9ec823/tar-0.2.11/src/lib.rs:409:25: 409:33 error: type `&std::fs::Metadata` does not implement any method in scope named `as_raw`
/home/hal/.cargo/registry/src/github.com-1ecc6299db9ec823/tar-0.2.11/src/lib.rs:409         let meta = meta.as_raw();
                                                                                                            ^~~~~~~~
error: aborting due to 2 previous errors
</pre>

**Comment by postmodern** [comment]
`Cargo.lock` lists libc v0.1.7.

**Comment by alexcrichton** [comment]
Thanks for the heads up!

**Comment by cadencemarseille** [comment]
Hi Alex,

Can you bump the version and publish the new version?  I am trying to publish [rust-pcre](https://github.com/cadencemarseille/rust-pcre) and the included libpcre-sys (which has a build dependency on this package), but `cargo publish` fails with "all dependencies must come from the same source" when I use:

<pre>
[build-dependencies.tar]
git = "https://github.com/alexcrichton/tar-rs"
</pre>

**Comment by alexcrichton** [comment]
Ah certainly! I just published 0.2.12
